spring.application.name=pos
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/adbms
spring.datasource.username=postgres
spring.datasource.password=me
spring.jpa.hibernate.ddl-auto=update
